'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NullDC_CvS2_BEAR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property be() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("be", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BEARJamma_ArcadeStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BEARJamma_ArcadeStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BEARJamma_Dreamcast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BEARJamma_Dreamcast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BEARJamma_Naomi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BEARJamma_Naomi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bj() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bj", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bu() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bu", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clippy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clippy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ConnectingNetplay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConnectingNetplay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Controls() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Controls", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DcClean() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DcClean", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property default_nullDC_dreamcast() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("default_nullDC_dreamcast", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property default_nullDC_naomi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("default_nullDC_naomi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Deps() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Deps", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.30
        '''CVS2::4B5360E5C101756B04FB20F11D50C8C8
        '''Dynarec.UnderclockFpu=1
        '''Emulation.ModVolMode=2
        '''Emulation.PaletteMode=2
        '''MVC2::9CE0220DCEF005912F3855D8BE98A35A
        '''Dynarec.UnderclockFpu=1
        '''Emulation.ModVolMode=2
        '''Emulation.AlphaSortMode=1
        '''SFA3::502D2FA89666019D8E8222F49F40431C
        '''Dreamcast.Cable=0
        '''Vampire Chronicle for Matching Service::A43F42016C786654ACF02A4AFBFFC260
        '''Dreamcast.Cable=0
        '''Power Stone 2::F6059501F9DCC894D716125BB0DFF6E1
        '''Emulation.AlphaSortMode=1
        '''Virtua_Tennis_2_Pal_Dc-Alpax::8649AE5A732BC808F228 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DreamcastGameOptimizations() As String
            Get
                Return ResourceManager.GetString("DreamcastGameOptimizations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainMenuBackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainMenuBackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property NewChallanger() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NewChallanger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property NewNullDCBearIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("NewNullDCBearIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NullDC_BEAR_UPDATER() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NullDC_BEAR_UPDATER", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NullDCBEAR_Title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NullDCBEAR_Title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NullNaomiClean() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NullNaomiClean", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SingleSquare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SingleSquare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Squares() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Squares", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThreeSquare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThreeSquare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Updates() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Updates", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property vmu_data_port01() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vmu_data_port01", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vs_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vs_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
