'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NullDC_CvS2_BEAR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property be() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("be", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BEARJamma_Dreamcast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BEARJamma_Dreamcast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BEARJammaNaomi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BEARJammaNaomi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Beta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Beta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bj() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bj", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property bu() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("bu", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clippy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clippy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Dpad_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Dpad_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Dpad_Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Dpad_Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Dpad_Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Dpad_Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Dpad_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Dpad_Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Guide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Guide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_LB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_LB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_LeftStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_LeftStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_LeftX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_LeftX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_LeftY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_LeftY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_LT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_LT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_RB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_RB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_RightStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_RightStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_RightX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_RightX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_RightY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_RightY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_RT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_RT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_X() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_X", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Controller_Y() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Controller_Y", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Controls() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Controls", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property DcClean() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DcClean", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property default_nullDC_dreamcast() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("default_nullDC_dreamcast", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property default_nullDC_naomi() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("default_nullDC_naomi", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Deps() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Deps", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dreamcast_ArcadeStick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dreamcast_ArcadeStick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.85
        '''CVS2::4B5360E5C101756B04FB20F11D50C8C8::5576B4A34D645C26C0BDE99D55F75FB0
        '''Dynarec.UnderclockFpu=1
        '''Emulation.ModVolMode=2
        '''Emulation.PaletteMode=2
        '''MVC2::9CE0220DCEF005912F3855D8BE98A35A::4A3B3DF3C475E9A0A01E0DE75FC0E87D::155E3EA07330912C61A93C1B4FD95B01
        '''Dynarec.UnderclockFpu=1
        '''Emulation.ModVolMode=2
        '''Emulation.AlphaSortMode=1
        '''Power Stone 2::F6059501F9DCC894D716125BB0DFF6E1::A09ED0A81635971E3D62431014D98F7A
        '''Emulation.AlphaSortMode=1
        '''CDDAMute=1
        '''Virtua_Tennis_2_Pal_Dc-Alpax::8649AE5A732BC808F228677B2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DreamcastGameOptimizations() As String
            Get
                Return ResourceManager.GetString("DreamcastGameOptimizations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gb_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gb_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gba_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gba_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_dreamcast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_dreamcast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_GBA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_GBA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_GBC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_GBC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_NES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_NES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_PSX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_PSX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_SNES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_SNES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property md_controller_3button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("md_controller_3button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property md_controller_6button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("md_controller_6button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mednafen() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mednafen", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property mednafen_server() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("mednafen_server", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to gb.system_type auto
        '''gba.bios 
        '''md.cdbios us_scd1_9210.bin
        '''md.input.auto 1
        '''md.region game
        '''md.reported_region same
        '''nes.fnscan 1
        '''nes.gg 0
        '''nes.ggrom gg.rom
        '''nes.input.fcexp none
        '''nes.nofs 0
        '''nes.pal 0
        '''nes.fnscan 1
        '''ngp.language english
        '''pce.input.multitap 1
        '''pce.arcadecard 1
        '''pce.cdbios syscard3.pce
        '''pce.disable_bram_cd 0
        '''pce.disable_bram_hucard 0
        '''pce.forcesgx 0
        '''pce.gecdbios gecard.pce
        '''pce_fast.arcadecard 1
        '''pce_fast.cdbios syscard3.pce
        '''pce_fast.cdspeed 1
        '''pce_fast.forcesgx 0
        '''pce_fast.ocmultiplier [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MednafenOptimizations() As String
            Get
                Return ResourceManager.GetString("MednafenOptimizations", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MessagePop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MessagePop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to md.input.multitap tp1
        '''pcfx.input.port1.multitap 1
        '''pcfx.input.port2.multitap 0
        '''psx.input.pport1.multitap 1
        '''psx.input.pport2.multitap 0
        '''snes.input.port1.multitap 1
        '''snes.input.port2.multitap 0
        '''snes_faust.input.sport1.multitap 1
        '''snes_faust.input.sport2.multitap 0
        '''ss.input.sport1.multitap 1
        '''ss.input.sport2.multitap 0.
        '''</summary>
        Friend ReadOnly Property Multitap_1() As String
            Get
                Return ResourceManager.GetString("Multitap_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to md.input.multitap tp2
        '''pcfx.input.port1.multitap 0
        '''pcfx.input.port2.multitap 1
        '''psx.input.pport1.multitap 0
        '''psx.input.pport2.multitap 1
        '''snes.input.port1.multitap 0
        '''snes.input.port2.multitap 1
        '''snes_faust.input.sport1.multitap 0
        '''snes_faust.input.sport2.multitap 1
        '''ss.input.sport1.multitap 0
        '''ss.input.sport2.multitap 1.
        '''</summary>
        Friend ReadOnly Property Multitap_2() As String
            Get
                Return ResourceManager.GetString("Multitap_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to md.input.multitap tpd
        '''pcfx.input.port1.multitap 1
        '''pcfx.input.port2.multitap 1
        '''psx.input.pport1.multitap 1
        '''psx.input.pport2.multitap 1
        '''snes.input.port1.multitap 1
        '''snes.input.port2.multitap 1
        '''snes_faust.input.sport1.multitap 1
        '''snes_faust.input.sport2.multitap 1
        '''ss.input.sport1.multitap 1
        '''ss.input.sport2.multitap 1.
        '''</summary>
        Friend ReadOnly Property Multitap_both() As String
            Get
                Return ResourceManager.GetString("Multitap_both", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to md.input.multitap none
        '''pcfx.input.port1.multitap 0
        '''pcfx.input.port2.multitap 0
        '''psx.input.pport1.multitap 0
        '''psx.input.pport2.multitap 0
        '''snes.input.port1.multitap 0
        '''snes.input.port2.multitap 0
        '''snes_faust.input.sport1.multitap 0
        '''snes_faust.input.sport2.multitap 0
        '''ss.input.sport1.multitap 0
        '''ss.input.sport2.multitap 0.
        '''</summary>
        Friend ReadOnly Property Multitap_None() As String
            Get
                Return ResourceManager.GetString("Multitap_None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nes_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nes_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nes_zapper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nes_zapper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property NewChallanger() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("NewChallanger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property NewNullDCBearIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("NewNullDCBearIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ngp_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ngp_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NullDC_BEAR_UPDATER() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NullDC_BEAR_UPDATER", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NullDCBEAR_Title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NullDCBEAR_Title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property NullNaomiClean() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NullNaomiClean", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property psx_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("psx_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property psx_dualanalogcontroller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("psx_dualanalogcontroller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rupee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rupee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SDL_Stable() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SDL_Stable", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snes_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snes_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property snes_superscope() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snes_superscope", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ss_controller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ss_controller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Updates() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Updates", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property vmu_data_port01() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("vmu_data_port01", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vs_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vs_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
